In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Pitimbu,BR,2021-08-06 20:19:46,-7.4706,-34.8086,79.39,75,50,17.49
1,1,Miri,MY,2021-08-06 20:19:46,4.4148,114.0089,77.14,94,20,2.30
2,2,Hermanus,ZA,2021-08-06 20:19:46,-34.4187,19.2345,53.91,82,0,5.66
3,3,Kruisfontein,ZA,2021-08-06 20:19:47,-34.0033,24.7314,50.88,91,7,3.20
4,4,Avarua,CK,2021-08-06 20:19:47,-21.2078,-159.7750,77.05,78,20,10.36

In [3]:
# Check datatypes for DataFrame.
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature. We use list comprehension for this in the next block of code below instead of this for loop.
#max_temp = city_data_df["Max Temp"]
#temps = []
#for temp in max_temp:
    #temps.append(max(temp,0))

In [6]:
# Heatmap of Temperature.

# 1. Assign the locations to an array of latitude and longitude pairs.
#Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# 2. Assign the weights variable to some values
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"] 
# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)

# 5. Add the heatmap layer.
fig.add_layer(heat_layer)
# 6. Call the figure back to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity.
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent cloudiness.
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of wind speed.
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [14]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                      (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Pitimbu,BR,2021-08-06 20:19:46,-7.4706,-34.8086,79.39,75,50,17.49
1,1,Miri,MY,2021-08-06 20:19:46,4.4148,114.0089,77.14,94,20,2.30
4,4,Avarua,CK,2021-08-06 20:19:47,-21.2078,-159.7750,77.05,78,20,10.36
7,7,Hilo,US,2021-08-06 20:16:09,19.7297,-155.0900,78.53,84,90,8.05
13,13,Cockburn Town,TC,2021-08-06 20:19:49,21.4612,-71.1419,82.76,76,3,14.05
15,15,Nishihara,JP,2021-08-06 20:19:50,26.1842,127.7558,82.06,89,40,14.97
22,22,Shenzhen,CN,2021-08-06 20:19:52,22.5455,114.0683,85.10,98,100,3.36
28,28,Cayenne,GF,2021-08-06 20:15:16,4.9333,-52.3333,86.04,79,9,3.00
30,30,Jamestown,US,2021-08-06 20:15:18,42.0970,-79.2353,84.18,50,75,12.66
31,31,Kaukauna,US,2021-08-06 20:19:54,44.2780,-88.2720,84.52,73,75,3.00

In [15]:
preferred_cities_df.count()

City_ID       203
City          203
Country       203
Date          203
Lat           203
Lng           203
Max Temp      203
Humidity      203
Cloudiness    203
Wind Speed    203
dtype: int64

In [17]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]]
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

C:\Users\chayd\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

             City Country  Max Temp      Lat       Lng Hotel Name
0         Pitimbu      BR     79.39  -7.4706  -34.8086
1            Miri      MY     77.14   4.4148  114.0089
4          Avarua      CK     77.05 -21.2078 -159.7750
7            Hilo      US     78.53  19.7297 -155.0900
13  Cockburn Town      TC     82.76  21.4612  -71.1419
15      Nishihara      JP     82.06  26.1842  127.7558
22       Shenzhen      CN     85.10  22.5455  114.0683
28        Cayenne      GF     86.04   4.9333  -52.3333
30      Jamestown      US     84.18  42.0970  -79.2353
31       Kaukauna      US     84.52  44.2780  -88.2720

In [18]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [27]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print("Hotel found")
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found

In [25]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [29]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))